version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    # ports:
      # - 5432:5432
  adminer:
    image: adminer:4.7.8-standalone
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
  app:
    image: neytreeno/testapp
    # build: ./TestWork
    restart: always
    depends_on:
      - db
